# Generated by Django 4.1.5 on 2023-01-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longname', models.CharField(max_length=100, unique=True, verbose_name='longname')),
                ('shortname', models.CharField(max_length=5, unique=True, verbose_name='shortname')),
                ('played', models.PositiveSmallIntegerField(default=0, verbose_name='played')),
                ('won', models.PositiveSmallIntegerField(default=0, verbose_name='won')),
                ('lost', models.PositiveSmallIntegerField(default=0, verbose_name='lost')),
                ('draw', models.PositiveSmallIntegerField(default=0, verbose_name='draw')),
                ('points', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='points')),
                ('nrr', models.FloatField(db_index=True, default=0, max_length=5, verbose_name='nrr')),
            ],
            options={
                'ordering': ('-points', '-nrr', 'shortname'),
            },
        ),
    ]
