# Generated by Django 4.1.5 on 2023-01-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=1, verbose_name='active'),
            preserve_default=False,
        ),
    ]
