# Generated by Django 4.1.5 on 2023-02-02 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_team_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('league', 'League'), ('qualifier 1', 'Qualifier 1'), ('qualifier 2', 'Qualifier 2'), ('eliminator', 'Eliminator'), ('final', 'Final')], default='league', max_length=20)),
                ('venue', models.CharField(max_length=200)),
                ('min_bet', models.PositiveSmallIntegerField(default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='scheduled', max_length=20)),
                ('t1score', models.JSONField(blank=True, null=True)),
                ('t2score', models.JSONField(blank=True, null=True)),
                ('double', models.BooleanField(default=False)),
                ('bat_first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bat_first_teams', to='teams.team')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='teams.team')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='teams.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_teams', to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ('num',),
            },
        ),
    ]
