# Generated by Django 4.1.5 on 2023-02-03 09:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='stats',
            field=models.JSONField(default=users.models.default_user_stats),
        ),
    ]
