# Generated by Django 4.1.5 on 2023-02-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraccount_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='amount'),
        ),
    ]
