# Generated by Django 4.1.5 on 2023-02-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useraccount_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ('-amount', 'name')},
        ),
    ]
