# Generated by Django 4.1.7 on 2023-03-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useraccount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
