# Generated by Django 4.1.5 on 2023-02-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_remove_matchhistory_t1score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchhistory',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='stats',
        ),
        migrations.AddField(
            model_name='teamstats',
            name='played',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='won',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='type',
            field=models.CharField(choices=[('all', 'All'), ('home', 'Home'), ('away', 'Away'), ('batFirst', 'Batfirst'), ('knockout', 'Knockout'), ('last10', 'Last10')], default='all', max_length=20),
        ),
    ]
