# Generated by Django 4.1.5 on 2023-02-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_active'),
        ('stats', '0004_alter_teamstats_unique_together_teamstats_stats_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamstats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='played',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='type',
            field=models.CharField(choices=[('all', 'All'), ('home', 'Home'), ('away', 'Away'), ('batFirst', 'Batfirst'), ('knockout', 'Knockout'), ('last10', 'Last10')], default='league', max_length=20),
        ),
        migrations.AddField(
            model_name='teamstats',
            name='won',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='teamstats',
            unique_together={('team1', 'team2', 'type')},
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='stats',
        ),
    ]
