# Generated by Django 4.1.5 on 2023-02-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_active'),
        ('stats', '0005_alter_teamstats_unique_together_teamstats_played_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamstats',
            unique_together={('team1', 'team2')},
        ),
        migrations.AddField(
            model_name='teamstats',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='played',
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='type',
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='won',
        ),
    ]
